Add condition for CI pipeline failure in case code quality gate fails, Fixes #23

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -44,6 +44,18 @@ jobs:
           .\.sonar\scanner\dotnet-sonarscanner begin /k:"CS455-Assignment-1_StackNServe" /o:"cs455-assignment-1" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
           dotnet build src/StackNServe/StackNServe.csproj
           .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
+      - name: Check SonarCloud Quality Gate
+        shell: bash
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          SONAR_STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=CS455-Assignment-1_StackNServe" | jq -r '.projectStatus.status')
+          if [ "$SONAR_STATUS" != "OK" ]; then
+            echo "Quality gate failed: $SONAR_STATUS"
+            exit 1
+          else
+            echo "Quality gate passed!"
+          fi
 
   deploy-to-github-pages:
     runs-on: ubuntu-latest
